# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'resume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cresume.proto\"\x81\x02\n\x06Resume\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x19\n\x07\x63ontact\x18\x03 \x01(\x0b\x32\x08.Contact\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x18\n\nexperience\x18\x05 \x03(\x0b\x32\x04.Job\x12\x1e\n\x06skills\x18\x06 \x03(\x0b\x32\x0e.SkillCategory\x12\x1a\n\x08projects\x18\x07 \x03(\x0b\x32\x08.Project\x12\x1d\n\teducation\x18\x08 \x03(\x0b\x32\n.Education\x12&\n\x0e\x63\x65rtifications\x18\t \x03(\x0b\x32\x0e.Certification\x12\x11\n\tlanguages\x18\n \x03(\t\"Z\n\x07\x43ontact\x12\r\n\x05phone\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08linkedin\x18\x03 \x01(\t\x12\x0e\n\x06github\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\"Y\n\x03Job\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x03(\t\"0\n\rSkillCategory\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\"L\n\x07Project\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\\\n\tEducation\x12\x0e\n\x06school\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65gree\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x0b\n\x03gpa\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63hievements\x18\x05 \x01(\t\";\n\rCertification\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06issuer\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESUME']._serialized_start=17
  _globals['_RESUME']._serialized_end=274
  _globals['_CONTACT']._serialized_start=276
  _globals['_CONTACT']._serialized_end=366
  _globals['_JOB']._serialized_start=368
  _globals['_JOB']._serialized_end=457
  _globals['_SKILLCATEGORY']._serialized_start=459
  _globals['_SKILLCATEGORY']._serialized_end=507
  _globals['_PROJECT']._serialized_start=509
  _globals['_PROJECT']._serialized_end=585
  _globals['_EDUCATION']._serialized_start=587
  _globals['_EDUCATION']._serialized_end=679
  _globals['_CERTIFICATION']._serialized_start=681
  _globals['_CERTIFICATION']._serialized_end=740
# @@protoc_insertion_point(module_scope)
